{{- if .Values.distributor.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex.fullname" . }}-distributor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cortex.name" . }}-distributor
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "cortex.chart" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "cortex.name" . }}-distributor
{{ toYaml .Values.distributor.podDisruptionBudget | indent 2 }}
{{- end -}}
